# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_academic', models.BooleanField(default=False)),
                ('is_facility', models.BooleanField(default=False)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('ai_analysis_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_proctor', 'Pending Proctor Review'), ('escalated', 'Escalated to Higher Body'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
