# Generated by Django 5.2.8 on 2025-11-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ai_analysis_json',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_dept_head', models.BooleanField(default=False)),
                ('campus', models.CharField(choices=[('tewodros', 'Tewodros Campus'), ('maraki', 'Maraki Campus'), ('cmhs', 'CMHS Campus')], default='tewodros', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('CS', 'Computer Science (CoI)'), ('IT', 'Information Technology (CoI)'), ('IS', 'Information Science (CoI)'), ('BIO', 'Biology (CNCS)'), ('PHY', 'Physics (CNCS)'), ('MAINT', 'Campus Maintenance')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
