# Generated by Django 5.2.8 on 2025-11-29 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_activitylog_passwordresettoken_and_more"),
        ("complaints", "0004_category_emailtemplate_remove_userprofile_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_translated", models.CharField(max_length=255)),
                ("description_translated", models.TextField()),
                ("from_language", models.CharField(default="am", max_length=10)),
                ("to_language", models.CharField(default="en", max_length=10)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Translation notes or context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "response_time_hours",
                    models.IntegerField(help_text="Time to first response in hours"),
                ),
                (
                    "resolution_time_hours",
                    models.IntegerField(help_text="Time to resolution in hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="complaint",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary for quick triage"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ai_urgency_confidence",
            field=models.FloatField(
                blank=True, help_text="AI confidence in urgency assessment", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ai_urgency_reason",
            field=models.TextField(
                blank=True, help_text="Explanation of AI urgency assessment"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="description_translated",
            field=models.TextField(
                blank=True, help_text="English translation of description"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User complaint was escalated to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalation_level",
            field=models.IntegerField(
                default=0,
                help_text="Escalation level: 0=none, 1=Dept Head, 2=Dean, 3=Campus Director, 4=Admin",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True, help_text="When first response was given", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="language",
            field=models.CharField(
                default="en", help_text="Language code: 'en' or 'am'", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="reopened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="reopened_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="complaint",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sentiment_label",
            field=models.CharField(
                blank=True,
                help_text="Sentiment label: positive/negative/neutral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sentiment_score",
            field=models.FloatField(
                blank=True, help_text="Sentiment analysis score (-1 to 1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sla_breach_notified_at",
            field=models.DateTimeField(
                blank=True, help_text="When SLA breach was notified", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sla_resolution_breached",
            field=models.BooleanField(
                default=False, help_text="Whether resolution SLA was breached"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sla_resolution_hours",
            field=models.IntegerField(
                blank=True, help_text="SLA resolution time in hours", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sla_response_breached",
            field=models.BooleanField(
                default=False, help_text="Whether response SLA was breached"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sla_response_hours",
            field=models.IntegerField(
                blank=True, help_text="SLA response time in hours", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="title_translated",
            field=models.CharField(
                blank=True, help_text="English translation of title", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="translation_confidence",
            field=models.FloatField(
                blank=True, help_text="Translation confidence score 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="translation_provider",
            field=models.CharField(
                blank=True, help_text="Translation service used", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="complaintevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("assigned", "Assigned"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("comment_added", "Comment Added"),
                    ("file_attached", "File Attached"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                    ("reopened", "Reopened"),
                    ("escalated", "Escalated"),
                    ("sla_breached", "SLA Breached"),
                    ("first_response", "First Response"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["language"], name="complaints__languag_57ffd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["escalated", "escalation_level"],
                name="complaints__escalat_d26d09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["sla_response_breached", "sla_resolution_breached"],
                name="complaints__sla_res_a9d4d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["is_duplicate"], name="complaints__is_dupl_9c1b04_idx"
            ),
        ),
        migrations.AddField(
            model_name="complainttranslation",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_translations",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complainttranslation",
            name="translated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slaconfiguration",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.campus",
            ),
        ),
        migrations.AddField(
            model_name="slaconfiguration",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="complaints.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slaconfiguration",
            unique_together={("priority", "category", "campus")},
        ),
    ]
